### ISSUE TITLE
V0.3.7 - error with multiple hosts

### ISSUE THREAD

**Issue by dhenry123** [aramperes/onetun#63]
**First of all, thank you for your work.**

(amd64) works fine with v0.3.6  but **since v0.3.7**, impossible to use with multiple hosts :

```bash
onetun-linux-amd64 --private-key 'hidden content' --endpoint-addr xxx.xxx.xxx.xxx:xxxxx --endpoint-public-key 'hidden content' --source-peer-ip xx.xx.xx.xx --keep-alive 25 127.0.0.1:41549:172.16.0.1:22 127.0.0.1:43029:172.16.0.2:22
```

ERROR: 
thread 'tokio-runtime-worker' panicked at src/virtual_iface/tcp.rs:97:37:
called `Result::unwrap()` on an `Err` value: Ipv4(Cidr { address: Address([172, 16, 0, 1]), prefix_len: 32 })

With **RUST_BACKTRACE=1**
```txt
thread 'tokio-runtime-worker' panicked at src/virtual_iface/tcp.rs:97:37:
called `Result::unwrap()` on an `Err` value: Ipv4(Cidr { address: Address([172, 16, 0, 1]), prefix_len: 32 })
stack backtrace:
 2024-11-30T20:50:29.861Z INFO  onetun::tunnel > Tunneling TCP [127.0.0.1:45317]->[172.16.0.1:22] (via [xxx.xxx.xxx.xxx:xxxxx] as peer xx.xx.xx.xx)
 2024-11-30T20:50:29.861Z INFO  onetun::tunnel > Tunneling TCP [127.0.0.1:40553]->[[172.16.0.2:22] (via [xxx.xxx.xxx.xxx:xxxxx] as peer xx.xx.xx.xx)
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
   3: smoltcp::iface::interface::Interface::update_ip_addrs
   4: <onetun::virtual_iface::tcp::TcpVirtualInterface as onetun::virtual_iface::VirtualInterfacePoll>::poll_loop::{{closure}}
   5: onetun::start_tunnels::{{closure}}::{{closure}}
   6: tokio::runtime::task::core::Core<T,S>::poll
   7: tokio::runtime::task::harness::Harness<T,S>::poll
   8: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run
  10: tokio::runtime::context::runtime::enter_runtime
  11: tokio::runtime::scheduler::multi_thread::worker::run
  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
```

Unable to connect to hosts
Thanks again

**Comment by aramperes** [comment]
Thanks for the bug report! This seems like it was un-tested during the migration to `smoltcp 0.10` (#58), which changed how IP ranges are assigned to the `Interface`.

In the mean-time using `v0.3.6` should work pretty much the same, without this defect.

**Comment by aramperes** [comment]
Latest version of `onetun` now supports concurrent tunnels up to 7 unique peers on the WireGuard network, per protocol. This was an oversight as recent versions of `smoltcp` reduced the number of addresses per interface from 4 to 2.

Should you need more unique IPs to tunnel to in the same process, `onetun` can be compiled with an increased limit inside `.cargo/config.toml.`

Thanks again for reporting this!
